import { test } from 'node:test';
import assert from 'node:assert/strict';

import { parseText } from '../src/perceiver/parse/index.js';
import { encodeLevels, attributedEvaluation, surfToAnswer } from '../src/surfer/index.js';

// surfToAnswer assembles the surf's reading into a structured result whose epistemics are
// GATED: a source channel (σ — cited document material + the narrator's attributed stance) and
// an interpretation channel (ρ — the reader's verdict) the surf withholds. These pin the gate.

const DOC =
  'CHAPTER I\n' +
  'The historians tell us the battle was won by genius. They say the great men shaped it.\n' +
  'CHAPTER II\n' +
  'Natasha watched the opera. Natasha saw the smooth boards and the painted cardboard.\n' +
  'CHAPTER III\n' +
  'Tushin loaded the cannon. Tushin cleaned the barrel.\n' +
  'CHAPTER IV\n' +
  'Pierre walked home. Pierre opened the door.';

const ctx = () => {
  const doc = parseText(DOC, { docId: 'a', totalRead: true });
  const encoding = encodeLevels(doc);
  const evaluation = attributedEvaluation(doc, encoding);
  return { doc, encoding, evaluation };
};

test('the result gates source (σ) from interpretation (ρ) as separate channels', () => {
  const c = ctx();
  const r = surfToAnswer('Analyze the defamiliarized opera scene and its moral project.', c);
  assert.ok(r.source && r.interpretation, 'two channels');
  assert.ok(Array.isArray(r.source.regions), 'source carries cited regions');
  assert.equal(r.interpretation.stance, null, 'the surf withholds the verdict');
  assert.equal(r.interpretation.generated, false, 'interpretation is not generated by the surf');
  assert.match(r.interpretation.discipline, /separate/i, 'the discipline is a separate, distinct channel');
});

test('every surfaced bond is cited to a sentence index with a verbatim quote (auditable)', () => {
  const c = ctx();
  const r = surfToAnswer('who loaded the cannon?', c);
  for (const reg of r.source.regions)
    for (const b of reg.bonds) {
      assert.ok(Number.isInteger(b.sentIdx), 'a bond cites its sentence');
      assert.equal(typeof b.quote, 'string', 'and carries the verbatim text to audit against');
    }
});

test('the narrator stance is owner-attributed, never the machine\'s — and never in interpretation', () => {
  const c = ctx();
  const r = surfToAnswer('Is the historians\' framing of the battle genuine or undercut?', c);
  if (r.source.narratorStance)
    assert.ok(/narrator|ambiguous/.test(r.source.narratorStance.owner), 'attributed to a mind in the text');
  // the machine's own verdict is never populated by the surf.
  assert.equal(r.interpretation.stance, null);
});

test('the modeler is wired into region selection — a meaning question surfaces its evaluative region', () => {
  const c = ctx();
  const r = surfToAnswer('Analyze the defamiliarized opera scene.', c);
  // the opera chapter (the defamiliarization locus) is reached, not buried under the plot beat.
  assert.ok(r.source.regions.some(reg => /CHAPTER II\b/.test(reg.title)), 'the opera region is surfaced');
});
